name: dispatcher
type: php
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "20"
hooks:
    post-start:
        - composer: install
        - exec: cd /var/www/html; npm ci
        - exec: cd /var/www/html; npm run dev
