name: Build and Test

on:
  workflow_call:

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
        
      - uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          dev: yes
          args: --ignore-platform-reqs

      - name: Run PHP linter
        run: "php vendor/bin/parallel-lint --no-progress src"

      - name: Run CodeSniffer with PSR12
        run: |
          mv phpcs.xml.dist phpcs.xml
          php vendor/bin/phpcs --standard=phpcs.xml

      - name: Run PHPStan
        run: |
          php bin/console cache:warmup --env=dev
          php bin/console cache:warmup --env=test
          mv phpstan.dist.neon phpstan.neon
          php vendor/bin/phpstan --no-progress
